# Use postgres/example user/password credentials
version: '3'

services:

  db:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - 127.0.0.1:${POSTGRES_LOCAL_PORT:-5432}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRED_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set and nonempty}

volumes:
  db_data:
    name: ${POSTGRES_DATA_VOLUME_NAME:-citybikesapp_db_data}