name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # .env.example can be used as is, except for the db password,
      # which will be injected into the environment separately.
      - name: Set up .env
        run: |
          cp .env.example .env
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.5.1 # use the explicit version number
        with:
          build: npm run build
          start: npm start
          command: npm run cypress
        env:
          POSTGRESS_PASSWORD: ${{ secrets.TESTING_POSTGRES_PASSWORD }}